name: Pipeline CI

on:
    push:
      branches:
        - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t "${{vars.ECR_IMAGE_URL}}" .

    - name: Push Docker image
      run: docker push ${{vars.ECR_IMAGE_URL}}